services:
  router1:
    image: quay.io/frrouting/frr:10.2.1
    container_name: router1
    privileged: true
    networks:
      lan_host:
        ipv4_address: 192.168.200.254
      wan1:
        ipv4_address: 23.10.49.2
      wan2:
        ipv4_address: 6.80.75.10
    volumes:
      - ./configs/r1/frr/:/etc/frr/
      - ./configs/r1/startup.sh:/etc/startup.sh
    sysctls:
      - net.ipv4.ip_forward=1
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 2s
      timeout: 2s
      retries: 5


  router2:
    image: quay.io/frrouting/frr:10.2.1
    container_name: router2
    privileged: true
    networks:
      wan2:
         ipv4_address: 6.80.75.11
      wan3:
         ipv4_address: 95.120.2.66
    volumes:
      - ./configs/r2/frr/:/etc/frr/
      - ./configs/r2/startup.sh:/etc/startup.sh
    sysctls:
      - net.ipv4.ip_forward=1
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 2s
      timeout: 2s
      retries: 5

  router3:
    image: quay.io/frrouting/frr:10.2.1
    container_name: router3
    privileged: true
    networks:
      lan_srv:
        ipv4_address: 192.168.201.254
      wan1:
        ipv4_address: 23.10.49.3
      wan3:
        ipv4_address: 95.120.2.67
    volumes:
      - ./configs/r3/frr/:/etc/frr/
      - ./configs/r3/startup.sh:/etc/startup.sh
    sysctls:
      - net.ipv4.ip_forward=1
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 2s
      timeout: 2s
      retries: 5


  host:
    image: alpine
    container_name: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/host/startup.sh:/etc/startup.sh
    networks:
      - lan_host
    command: ["sh", "-c", "while true; do sleep 30; done"]
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 2s
      timeout: 2s
      retries: 5

  srv:
    image: nginx
    container_name: srv
    networks:
      lan_srv:
        ipv4_address: 192.168.201.2
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/srv/startup.sh:/etc/startup.sh
    command: ["sh", "-c", "while true; do sleep 30; done"]
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 2s
      timeout: 2s
      retries: 5
  
  frr-script-runner:
    image: docker:cli
    depends_on:
      router1:
        condition: service_healthy
      router2:
        condition: service_healthy
      router3:
        condition: service_healthy
      host:
        condition: service_healthy
      srv:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "sleep 3 && /etc/startup.sh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/runner/startup.sh:/etc/startup.sh


networks:
  wan1:
    name: wan1
    ipam:
      driver: default
      config:
        - subnet: 23.10.49.0/29
  wan2:
    name: wan2
    ipam:
      driver: default
      config:
        - subnet: 6.80.75.8/29
  wan3:
    name: wan3
    ipam:
      driver: default
      config:
        - subnet: 95.120.2.64/29
  lan_host:
    name: lan_host
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
  lan_srv:
    name: lan_srv
    ipam:
      driver: default
      config:
        - subnet: 192.168.201.0/24