services:
  router1:
    image: quay.io/frrouting/frr:10.2.1
    container_name: router1
    privileged: true
    networks:
      lan_host:
        ipv4_address: 10.10.10.254
      wan1:
        ipv4_address: 10.10.99.2
    volumes:
      - ./configs/r1/frr/:/etc/frr/
      - ./configs/r1/startup-exA.sh:/etc/startup-exA.sh
    sysctls:
      - net.ipv4.ip_forward=1
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 2s
      timeout: 2s
      retries: 5


  router2:
    image: quay.io/frrouting/frr:10.2.1
    container_name: router2
    privileged: true
    networks:
      wan2:
         ipv4_address: 10.10.99.11
      lan_srv:
         ipv4_address: 10.10.11.254
    volumes:
      - ./configs/r2/frr/:/etc/frr/
      - ./configs/r2/startup-exA.sh:/etc/startup-exA.sh
    sysctls:
      - net.ipv4.ip_forward=1
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 2s
      timeout: 2s
      retries: 5
  
  router3:
    image: quay.io/frrouting/frr:10.2.1
    container_name: router3
    privileged: true
    networks:
      wan1:
         ipv4_address: 10.10.99.3
      wan2:
         ipv4_address: 10.10.99.10
    volumes:
      - ./configs/r3/frr/:/etc/frr/
      - ./configs/r3/startup-exA.sh:/etc/startup-exA.sh
    sysctls:
      - net.ipv4.ip_forward=1
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 2s
      timeout: 2s
      retries: 5

  host:
#    para testar conectividade com o servidor:
#    wget http://55.73.20.2 --spider
    image: alpine
    container_name: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/host/startup.sh:/etc/startup.sh
    networks:
      - lan_host
    command: ["sh", "-c", "while true; do sleep 30; done"]
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 2s
      timeout: 2s
      retries: 5

  srv:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: sistca/nginx
    container_name: srv
    networks:
      lan_srv:
        ipv4_address: 10.10.11.2
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/srv/startup.sh:/etc/startup.sh
    command: ["sh", "-c", "while true; do sleep 30; done"]
    healthcheck:
      test: ["CMD", "echo", "healthy"]
      interval: 2s
      timeout: 2s
      retries: 5
  
  frr-script-runner:
    image: docker:cli
    depends_on:
      router1:
        condition: service_healthy
      router2:
        condition: service_healthy
      router3:
        condition: service_healthy
      host:
        condition: service_healthy
      srv:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "sleep 3 && /etc/startup-exA.sh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/runner/startup-exA.sh:/etc/startup-exA.sh


networks:
  wan1:
    name: wan1
    ipam:
      driver: default
      config:
        - subnet: 10.10.99.0/29
  wan2:
    name: wan2
    ipam:
      driver: default
      config:
        - subnet: 10.10.99.8/29
  lan_host:
    name: lan_host
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
  lan_srv:
    name: lan_srv
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.0/24