services:
  router1:
    image: quay.io/frrouting/frr:10.2.1
    container_name: router1
    privileged: true
    networks:
      lan_host:
        ipv4_address: 10.10.10.254
      wan1:
        ipv4_address: 10.10.99.2
    volumes:
      - ./configs/r1/frr/:/etc/frr/
      - ./configs/r1/startup-tutorial.sh:/etc/startup-tutorial.sh
    sysctls:
      - net.ipv4.ip_forward=1
    healthcheck:
      test: [ "CMD", "echo", "healthy" ]
      interval: 2s
      timeout: 2s
      retries: 5


  router2:
    image: quay.io/frrouting/frr:10.2.1
    container_name: router2
    privileged: true
    networks:
      wan1:
        ipv4_address: 10.10.99.3
      lan_srv:
        ipv4_address: 10.10.11.254
    volumes:
      - ./configs/r2/frr/:/etc/frr/
      - ./configs/r2/startup-tutorial.sh:/etc/startup-tutorial.sh
    sysctls:
      - net.ipv4.ip_forward=1
    healthcheck:
      test: [ "CMD", "echo", "healthy" ]
      interval: 2s
      timeout: 2s
      retries: 5

  host:
    #   Para testar conectividade com o servidor:
    #   --spider   : permite confirmar a existência de um qualquer ficheiro no destino.
    #   --timeout  : permite definir um timeout para a resposta do servidor.
    #
    #   wget http://10.10.11.2 --spider --timeout 2
    #
    image: alpine
    container_name: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/host/startup.sh:/etc/startup.sh
    networks:
      - lan_host
    command: [ "sh", "-c", "while true; do sleep 30; done" ]
    healthcheck:
      test: [ "CMD", "echo", "healthy" ]
      interval: 2s
      timeout: 2s
      retries: 5

  srv:
    build:
      context: .
      dockerfile: Dockerfile-srv
    image: sistca/srv
    container_name: srv
    networks:
      lan_srv:
        ipv4_address: 10.10.11.2
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/srv/startup.sh:/etc/startup.sh
    command: [ "sh", "-c", "while true; do sleep 30; done" ]
    healthcheck:
      test: [ "CMD", "echo", "healthy" ]
      interval: 2s
      timeout: 2s
      retries: 5
  
  frr-script-runner:
    image: docker:cli
    depends_on:
      router1:
        condition: service_healthy
      router2:
        condition: service_healthy
      host:
        condition: service_healthy
      srv:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "-c", "sleep 3 && /etc/startup-tutorial.sh" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/runner/startup-tutorial.sh:/etc/startup-tutorial.sh


networks:
  wan1:
    name: wan1
    ipam:
      driver: default
      config:
        - subnet: 10.10.99.0/29
  lan_host:
    name: lan_host
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
  lan_srv:
    name: lan_srv
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.0/24