services:
  router1:
    build:
      context: .
      dockerfile: Dockerfile-router1
    image: sistca/router1
    #image: quay.io/frrouting/frr:10.2.1
    container_name: router1
    privileged: true
    networks:
      lan_host:
        ipv4_address: 10.10.10.254
      wan1:
        ipv4_address: 10.10.99.2
      wan3:
        ipv4_address: 10.10.99.18
    volumes:
      - ./configs/r1/frr/daemons:/etc/frr/daemons
      - ./configs/r1/startup-challenge.sh:/etc/startup-challenge.sh
    sysctls:
      - net.ipv4.ip_forward=1
    healthcheck:
      test: [ "CMD", "echo", "healthy" ]
      interval: 2s
      timeout: 2s
      retries: 5


  router2:
    image: quay.io/frrouting/frr:10.2.1
    container_name: router2
    privileged: true
    networks:
      wan2:
        ipv4_address: 10.10.99.11
      wan4:
        ipv4_address: 10.10.99.27
      lan_srv:
        ipv4_address: 10.10.11.254
    volumes:
      - ./configs/r2/frr/daemons:/etc/frr/daemons
      - ./configs/r2/startup-challenge.sh:/etc/startup-challenge.sh
    sysctls:
      - net.ipv4.ip_forward=1
    healthcheck:
      test: [ "CMD", "echo", "healthy" ]
      interval: 2s
      timeout: 2s
      retries: 5
  
  router3:
    image: quay.io/frrouting/frr:10.2.1
    container_name: router3
    privileged: true
    networks:
      wan1:
        ipv4_address: 10.10.99.3
      wan2:
        ipv4_address: 10.10.99.10
    volumes:
      - ./configs/r3/frr/daemons:/etc/frr/daemons
      - ./configs/r3/startup-challenge.sh:/etc/startup-challenge.sh
    sysctls:
      - net.ipv4.ip_forward=1
    healthcheck:
      test: [ "CMD", "echo", "healthy" ]
      interval: 2s
      timeout: 2s
      retries: 5

  router4:
    image: quay.io/frrouting/frr:10.2.1
    container_name: router4
    privileged: true
    networks:
      wan3:
        ipv4_address: 10.10.99.19
      wan4:
        ipv4_address: 10.10.99.26
    volumes:
      - ./configs/r4/frr/daemons:/etc/frr/daemons
      - ./configs/r4/startup-challenge.sh:/etc/startup-challenge.sh
    sysctls:
      - net.ipv4.ip_forward=1
    healthcheck:
      test: [ "CMD", "echo", "healthy" ]
      interval: 2s
      timeout: 2s
      retries: 5

  host:
    #   Para testar conectividade com o servidor:
    #   --spider   : permite confirmar a existência de um qualquer ficheiro no destino.
    #   --timeout  : permite definir um timeout para a resposta do servidor.
    #
    #   wget http://10.10.11.2 --spider --timeout 2
    #
    #image: alpine
    build:
      context: .
      dockerfile: Dockerfile-host
    image: sistca/host
    container_name: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/host/startup.sh:/etc/startup.sh
    networks:
      - lan_host
    command: [ "sh", "-c", "while true; do sleep 30; done" ]
    healthcheck:
      test: [ "CMD", "echo", "healthy" ]
      interval: 2s
      timeout: 2s
      retries: 5

  srv:
    build:
      context: .
      dockerfile: Dockerfile-srv
    image: sistca/srv
    container_name: srv
    networks:
      lan_srv:
        ipv4_address: 10.10.11.2
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/srv/startup.sh:/etc/startup.sh
    command: [ "sh", "-c", "while true; do sleep 30; done" ]
    healthcheck:
      test: [ "CMD", "echo", "healthy" ]
      interval: 2s
      timeout: 2s
      retries: 5
  
  frr-script-runner:
    image: docker:cli
    depends_on:
      router1:
        condition: service_healthy
      router2:
        condition: service_healthy
      router3:
        condition: service_healthy
      router4:
        condition: service_healthy
      host:
        condition: service_healthy
      srv:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "-c", "sleep 3 && /etc/startup-challenge.sh" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/runner/startup-challenge.sh:/etc/startup-challenge.sh


networks:
  wan1:
    name: wan1
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: frr-wan1br
    ipam:
      config:
        - subnet: 10.10.99.0/29
  wan2:
    name: wan2
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: frr-wan2br
    ipam:
      config:
        - subnet: 10.10.99.8/29
  wan3:
    name: wan3
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: frr-wan3br
    ipam:
      config:
        - subnet: 10.10.99.16/29
  wan4:
    name: wan4
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: frr-wan4br
    ipam:
      config:
        - subnet: 10.10.99.24/29
  lan_host:
    name: lan_host
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
  lan_srv:
    name: lan_srv
    ipam:
      driver: default
      config:
        - subnet: 10.10.11.0/24