@startuml
' https://plantuml.com/component-diagram

title Rede Tutorial

rectangle "host" as Host
rectangle "router1" as Router1
rectangle "router2" as Router2
rectangle "srv" as Server

Host "10.10.10.x\n(DHCP)" --> "10.10.10.254" Router1 : "lan_host\n10.10.10.0/24"

Router1 "10.10.99.2" ---> "10.10.99.3" Router2 : wan1\n(10.10.99.0/29)

Router2 "10.10.11.254" --> "10.10.11.2" Server : srv_lan\n(10.10.11.0/24)

@enduml